version: "3.3"

services:
  postgres:
    image: postgres:14.1-alpine
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 3666:5432
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - data:/data
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - 3333:3333
    logging:
      driver: 'none'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
volumes:
  db:
  data:
  # proservice:
  #   command: dev
  #   port:
  #     - 3000:3000
  #   build:
  #     context: packages/landingpage
  #     dockerfile: Dockerfile
  #   volume:
  #     - ./pro:/usr/src/app
  #     - /usr/src/app/node_modules
  #     - /usr/src/app/.next
  #   env_file:
  #     - .env